const calculators={
 mortgage:{icon:"🏠",title:"Mortgage Calculator",subtitle:"Estimate your monthly mortgage payment and total interest.",fields:[["amount","Loan amount (€)",200000],["rate","Annual interest rate (%)",3.5,"0.1"],["term","Term (years)",30]],button:"Calculate monthly payment",calculate:v=>{const p=v.amount,r=v.rate/1200,n=v.term*12,m=r?p*r*(1+r)**n/((1+r)**n-1):p/n;return [["Monthly payment",m],["Total paid",m*n],["Total interest",m*n-p]]}},
 loan:{icon:"💰",title:"Personal Loan Calculator",subtitle:"Estimate your monthly payment and the full cost of a personal loan.",fields:[["amount","Loan amount (€)",10000],["rate","Annual interest rate (%)",5,"0.1"],["term","Term (months)",60]],button:"Calculate monthly payment",calculate:v=>{const r=v.rate/1200,n=v.term,m=r?v.amount*r*(1+r)**n/((1+r)**n-1):v.amount/n;return [["Monthly payment",m],["Total paid",m*n],["Total interest",m*n-v.amount]]}},
 compound:{icon:"📈",title:"Compound Interest Calculator",subtitle:"See how your money can grow over time.",fields:[["initial","Initial amount (€)",10000],["rate","Annual return (%)",7,"0.1"],["years","Years",20],["monthly","Monthly contribution (€)",200]],button:"Calculate growth",calculate:v=>{const r=v.rate/1200,n=v.years*12,total=v.initial*(1+r)**n+(r?v.monthly*((1+r)**n-1)/r:v.monthly*n),contributed=v.initial+v.monthly*n;return [["Final balance",total],["Total contributed",contributed],["Investment growth",total-contributed]]}},
 savings:{icon:"🎯",title:"Savings Goal Calculator",subtitle:"Find the monthly amount needed to reach your goal.",fields:[["goal","Savings goal (€)",50000],["current","Current savings (€)",5000],["rate","Annual interest rate (%)",4,"0.1"],["years","Time (years)",10]],button:"Calculate monthly savings",calculate:v=>{const r=v.rate/1200,n=v.years*12,future=v.current*(1+r)**n,monthly=r?(v.goal-future)*r/((1+r)**n-1):(v.goal-v.current)/n;return [["Monthly savings needed",Math.max(0,monthly)],["Target amount",v.goal],["Time",v.years," years"]]}},
 debt:{icon:"💳",title:"Debt Payoff Calculator",subtitle:"Estimate how long it will take to pay off your debt.",fields:[["balance","Debt balance (€)",5000],["rate","Annual interest rate (%)",18,"0.1"],["payment","Monthly payment (€)",200]],button:"Calculate payoff",calculate:v=>{const r=v.rate/1200;if(v.payment<=v.balance*r)throw new Error("The payment must be higher than the monthly interest.");const n=r?Math.ceil(-Math.log(1-v.balance*r/v.payment)/Math.log(1+r)):Math.ceil(v.balance/v.payment),total=v.payment*n;return [["Time to pay off",n," months"],["Estimated total paid",total],["Estimated interest",total-v.balance]]}},
 budget:{icon:"📊",title:"50/30/20 Budget Calculator",subtitle:"Split your monthly income into needs, wants and savings.",fields:[["income","Monthly net income (€)",1500]],button:"Build my budget",calculate:v=>[["Needs (50%)",v.income*.5],["Wants (30%)",v.income*.3],["Savings and debt (20%)",v.income*.2]]},
 vat:{icon:"🧾",title:"VAT Calculator",subtitle:"Add or remove VAT from any amount.",fields:[["amount","Amount (€)",100],["rate","VAT rate (%)",21,"0.1"]],button:"Calculate VAT",calculate:v=>[["VAT amount",v.amount*v.rate/100],["Price including VAT",v.amount*(1+v.rate/100)]]},
 salary:{icon:"💼",title:"Gross to Net Salary Calculator",subtitle:"Get a simple estimate of your take-home salary in Spain.",fields:[["gross","Annual gross salary (€)",30000],["tax","Estimated income tax (%)",15,"0.1"],["social","Social Security (%)",6.35,"0.01"]],button:"Estimate net salary",calculate:v=>{const net=v.gross*(1-(v.tax+v.social)/100);return [["Estimated annual net salary",net],["Estimated monthly net salary",net/12],["Estimated deductions",v.gross-net]]}},
 tip:{icon:"🍽️",title:"Tip Calculator",subtitle:"Split a bill and tip between any number of people.",fields:[["bill","Bill total (€)",50],["tip","Tip (%)",15,"1"],["people","Number of people",1]],button:"Calculate tip",calculate:v=>{const tip=v.bill*v.tip/100,total=v.bill+tip;return [["Tip",tip],["Total bill",total],["Per person",total/Math.max(1,v.people)]]}}
};
const key=document.body.dataset.calculator,c=calculators[key],form=document.getElementById("calculator");
document.title=`${c.title} | CalculadoraFinanzas`;document.getElementById("page-title").textContent=`${c.icon} ${c.title}`;document.getElementById("page-subtitle").textContent=c.subtitle;document.getElementById("calc-title").textContent=c.title;
c.fields.forEach(([id,label,value,step])=>{form.insertAdjacentHTML("beforeend",`<label for="${id}">${label}</label><input id="${id}" type="number" value="${value}" step="${step||1}" required>`)});form.insertAdjacentHTML("beforeend",`<button type="submit">${c.button}</button><div class="result" id="result"></div>`);
form.addEventListener("submit",e=>{e.preventDefault();const values={};c.fields.forEach(([id])=>values[id]=Number(document.getElementById(id).value));const out=document.getElementById("result");try{const rows=c.calculate(values);out.innerHTML=rows.map(([label,value,suffix=""])=>`<strong>${label}:</strong> ${suffix?Number(value).toLocaleString("en-GB",{maximumFractionDigits:1})+suffix:Number(value).toLocaleString("en-GB",{style:"currency",currency:"EUR"})}`).join("<br>");}catch(err){out.textContent=err.message}out.style.display="block"});
